const MARKET_INDICES = [
  {
    slug: 'dow',
    symbol: '^DJI',
    label: '다우존스 산업지수',
    shortLabel: 'Dow Jones',
    region: '미국',
    coveredCall: 'DJIA',
    etf: 'DIA',
  },
  {
    slug: 'nasdaq',
    symbol: '^IXIC',
    label: '나스닥 종합지수',
    shortLabel: 'NASDAQ',
    region: '미국',
    coveredCall: null,
    etf: null,
  },
  {
    slug: 'sp500',
    symbol: '^GSPC',
    label: 'S&P 500 지수',
    shortLabel: 'S&P 500',
    region: '미국',
    coveredCall: 'JEPI',
    etf: 'SPY',
  },
  {
    slug: 'nasdaq100',
    symbol: '^NDX',
    label: '나스닥 100 지수',
    shortLabel: 'NASDAQ 100',
    region: '미국',
    coveredCall: 'JEPQ',
    etf: 'QQQ',
  },
  {
    slug: 'vix',
    symbol: '^VIX',
    label: 'CBOE 변동성 지수',
    shortLabel: 'VIX',
    region: '미국',
    coveredCall: null,
    etf: null,
  },
  {
    slug: 'china-internet',
    symbol: 'H30533.SS',
    label: 'CSI Overseas China Internet',
    shortLabel: 'China Internet',
    region: '중국',
    coveredCall: 'KLIP',
    etf: 'KWEB',
  },
  {
    slug: 'kospi',
    symbol: '^KS11',
    label: '코스피 지수',
    shortLabel: 'KOSPI',
    region: '대한민국',
    coveredCall: null,
    etf: null,
  },
  {
    slug: 'kosdaq',
    symbol: '^KQ11',
    label: '코스닥 지수',
    shortLabel: 'KOSDAQ',
    region: '대한민국',
    coveredCall: null,
    etf: null,
  },
];

module.exports = {
  MARKET_INDICES,
};
